const images = [
"Dr Oetker Veg Mayonnaise Smoky Peri Peri 1kg.png",
"Dr Oetker Funfoods Italian Style Pasta And Pizza Sauce 1kg.png",
"Dr Oetker Funfoods Makhani Sauce For Pasta And Pizza 1kg.png",
"Dr Oetker Funfoods Salad Mayonnaise 1kg.png",
"Dr Oetker Italian Style Pasta And Pizza Sauce No Onion No Garlic 1kg.png",
"GGF - Pav Bread.png",
"GGF - Pizza Base By GGF.png",
"Puliro American Bread Crumb.png",
"Puliro Bread Crumb.png",
"Puliro Panko Bread Crumb.png",
"Sriraja Panich - Sriraja Chilli Sauce, 570 gm.png",
"Woh Hup - Black Pepper Sauce, 340 gm.png",
"Woh Hup - Spicy Black Bean Sauce, 340 gm.png",
"Godrej Yummiez Crispy Veg Sticks 320gm.png",
"Amul Mithai Mate.png",
"GGF - Burger Bun.png",
"Finosta Penne Pasta.png",
"Frozen Basa Fillets.png",
"GC MSG.png",
"Go Cheese Slices, 750 g (50 g Free) (50 pcs x 16 g).png",
"Godrej Yummiez Chicken Burger 300gm.png",
"Godrej Yummiez Chicken Nuggets 500gm.png",
"Godrej Yummiez Chilli Garlic Potato Bites 420g.png",
"Godrej Yummiez Veg Burger Patty 340gm.png",
"Goeld.png",
"GGF - Jumbo Sandwich Bread.png",
"Madras Ship Curry.jpg",
"McCain CrispONs.jpg",
"mccain-onion-rings-110605.jpg",
"Nature Smith Smoked Paprika Powder 400g.jpg",
"NATURESMITH PAPRIKA POWDER-400g.jpg",
"Godrej Yummiez Cheesy Pizza Finger.jpg",
"Nestle Maggi.jpg",
"Nestle KitKat.jpg",
"Golden Crown Beans In Tomato Sauce 450 gm Golden Crown.jpg",
"Delta Toffee Caramel 1kg.jpg",
"Finosta Fusilli Pasta.jpg",
"Finosta Spaghetti Pasta.jpg",
"Food Coast Mayo Lite, 1 kg.jpg",
"frozen-momoz.jpg",
"Lotus Biscof Smooth Creamy Spread.jpg",
"Lotus Biscofs Biscuits.jpg",
"Namjai - Tom Yum Soup Paste (Veg), 1 Kg.jpeg",
"Chef's Art Hyderabadi Biryani Powder Masala - 500g.jpeg",
"Go filler cheese 500g.jpeg",
];
